### ISSUE TITLE
Requirement VaadinAccessDeniedHandler

### ISSUE THREAD

**Issue by GJRTimmer** [peholmst/vaadin4spring#166]
spring-vaadin-security requires a custom ```AccessDeniedHandler```

Situation:
- MainUI with annotations
    - ```SpringViewProvider``` setup as navigator.
- Single view, mapped to ```""``` (Main view)
    - Secured with a ```@Secured``` annotation.

The problem found is that the ```SpringViewProvider``` does not get a chance to check the view because, it's the main view, and the request has not reached the MainUI from the chain, the SpringViewProvider is only used when accessing views through Vaadin navigation calls.

The SecurityFilterChain however is able to see that the MainView object in question is secured and does the following:

```log
20:54:39.696  | DEBUG | o.s.s.w.a.i.FilterSecurityInterceptor                             | beforeInvocation:194                | Secure object: FilterInvocation: URL: /; Attributes: [hasRole('ROLE_USER')]
20:54:39.696  | DEBUG | o.s.s.w.a.i.FilterSecurityInterceptor                             | authenticateIfRequired:310          | Previously Authenticated: org.springframework.security.authentication.UsernamePasswordAuthenticationToken@d19a66cc: Principal: org.springframework.security.core.userdetails.User@2dc2cc: Username: anon; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_ANONYMOUS; Credentials: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: ROLE_ANONYMOUS
20:54:39.696  | DEBUG | o.s.s.a.v.AffirmativeBased                                        | decide:65                           | Voter: org.springframework.security.web.access.expression.WebExpressionVoter@23134312, returned: -1
20:54:39.696  | INFO  | o.s.b.a.a.l.AuditListener                                         | onApplicationEvent:42               | AuditEvent [timestamp=Wed Feb 04 20:54:39 CET 2015, principal=anon, type=AUTHORIZATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]
20:54:39.696  | DEBUG | n.e.i.c.a.l.LoggingAspect                                         | logAround:45                        | Enter: org.springframework.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent [timestamp=Wed Feb 04 20:54:39 CET 2015, principal=anon, type=AUTHORIZATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]]
Hibernate: insert into AUTH__AUDIT_EVENT (EVENT_DATE, EVENT_TYPE, PRINCIPAL) values (?, ?, ?)
Hibernate: insert into AUTH__AUDIT_EVENT_DATA (ID, NAME, VALUE) values (?, ?, ?)
Hibernate: insert into AUTH__AUDIT_EVENT_DATA (ID, NAME, VALUE) values (?, ?, ?)
20:54:39.711  | DEBUG | n.e.i.c.a.l.LoggingAspect                                         | logAround:51                        | Exit: org.springframework.boot.actuate.audit.AuditEventRepository.add() with result = null
20:54:39.711  | DEBUG | o.s.s.w.a.ExceptionTranslationFilter                              | handleSpringSecurityException:172   | Access is denied (user is not anonymous); delegating to AccessDeniedHandler
org.springframework.security.access.AccessDeniedException: Access is denied
	at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:83) ~[spring-security-core-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:206) ~[spring-security-core-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84) ~[spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342) [spring-security-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]

...

```

1) ```FilterSecurityInterceptor``` denies access to the secured object
2) ```ExceptionTranslationFilter``` kicks in and handles the ```AccessDeniedException```

This redirects the browser to the default spring ```/error``` mapping and generates a default error page when none is configured.

This is correct behavior of spring-security but not desirable for a Vaadin app.

Need for a custom AccessDeniedHandler and optionally exclude the AccessDeniedExceptions from the ```ExceptionTranslationFilter``` so the exceptions get passed correctly.

<h4>First implementation suggestion</h4>
- Redirect the user to a unsecured View

Unsecured view shows a nice Access denied message to the user to ensure that the user does not leave the Vaadin Framework / application. Currently this happens because you get redirect to ```/error```

This redirect is configured through the constructor of the AccessDeniedHandler so that it is enforced as required.

An other suggestion is welcome.

**Comment by GJRTimmer** [comment]
@Closed, not longer an issue, exception was thrown due to incorrect configuration of Spring-Security.

Personal error.

**Comment by manish211** [comment]
Could you please elaborate on what was the mistake and how you corrected the same in the configuration of Spring-Security?

**Comment by GJRTimmer** [comment]
I will look into my code so see what caused it.
