### ISSUE TITLE
Missing Authentication object in SecurityContext when using @Secured annotation

### ISSUE THREAD

**Issue by LarsMilland** [peholmst/vaadin4spring#185]
Navigation from one view to another using "navigateTo" is not working when the target view of the navigation is annotated with a @Secured("ROLE_USER") annotation.

In trying to use the Vaadin Spring Security implementation of your project, which works just fine for the initial load of a secured view, the problem occurs when navigating across to another view as shown here with a sample from a button click event:

UI.getCurrent().getNavigator().navigateTo(SecuredView.NAME);

This throws exceptions as this:

org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:339)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:198)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:60)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy100.enter(Unknown Source)
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:578)

This also occurs in the sample application included in your project if that is extended with the @Secured annotation and some views to navigate back and forth against.

Perhaps the security context with the authenticated user established during the login needs to be fixed somewhere such Spring can find and use it across all the application. Maybe this is solveable with some configuration code catching the authentication success event or similar.

**Comment by GJRTimmer** [comment]
Reproduced

**Comment by GJRTimmer** [comment]
Problem is caused because /UIDL/** which allows communication between Vaadin Server and Client is added to the ignored chain, this causes the described behavior. Because the /UIDL/** request / responses are not authenticated, not even with a ROLE_ANONYMOUS.

**Comment by GJRTimmer** [comment]
@LarsMilland please check updated security-sample
