### ISSUE TITLE
Atmosphere in production

### ISSUE THREAD

**Issue by markoradinovic** [peholmst/vaadin4spring#187]
Hi,
I'm getting this exception on application startup.

```java
java.lang.AssertionError: Not a File: file:/opt/hotmark-webmail/hotmark-webmail-0.0.1-SNAPSHOT.jar!/lib/atmosphere-runtime-2.1.2.vaadin6.jar
	at org.atmosphere.util.annotation.AnnotationDetector.detect(AnnotationDetector.java:352)
	at org.atmosphere.cpr.DefaultAnnotationProcessor.scanForAnnotation(DefaultAnnotationProcessor.java:147)
	at org.atmosphere.cpr.DefaultAnnotationProcessor.configure(DefaultAnnotationProcessor.java:133)
	at org.atmosphere.cpr.AtmosphereFramework.autoConfigureService(AtmosphereFramework.java:2280)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:707)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:614)
	at com.vaadin.server.communication.PushRequestHandler.<init>(PushRequestHandler.java:123)
	at com.vaadin.server.VaadinServletService.createRequestHandlers(VaadinServletService.java:82)
	at com.vaadin.server.VaadinService.init(VaadinService.java:186)
	at com.vaadin.server.VaadinServlet.createServletService(VaadinServlet.java:258)
	at com.vaadin.server.VaadinServlet.init(VaadinServlet.java:164)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:612)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:395)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedWebAppContext$JettyEmbeddedServletHandler.deferredInitialize(JettyEmbeddedWebAppContext.java:46)
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedWebAppContext.deferredInitialize(JettyEmbeddedWebAppContext.java:36)
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.handleDeferredInitialize(JettyEmbeddedServletContainer.java:162)
	at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.start(JettyEmbeddedServletContainer.java:109)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:287)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
	at com.hotmark.webmail.WebMailApplication.main(WebMailApplication.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
	at java.lang.Thread.run(Thread.java:745)
```

This is only happening when running  as a packaged application (java -jar application.jar).

It's seems like this doesn't affect Push communication.

**Comment by KyleRogers** [comment]
I think this is not a vaadin4spring but an embedded tomcat with atmosphere issue. See  https://github.com/jhipster/generator-jhipster/issues/471 and https://github.com/Atmosphere/atmosphere/issues/1706

You can try to upgrade to latest atmosphere 2.2.3+

**Comment by markoradinovic** [comment]
Ok, thanks.
