### ISSUE TITLE
I18N violates contract of java.io.Serializable

### ISSUE THREAD

**Issue by benheilers** [peholmst/vaadin4spring#198]
When stopping tomcat we see the below exception.  By using a remote debugger with a breakpoint on line 1183 of ObjectOutputStream, I found that the problem is the field I18N.applicationContext.

You have marked the class org.vaadin.spring.i18n.I18N as Serializable, but you've provided it with a field applicationContext which frequently does not implement Serializable (and - I think - it doesn't make sense to expect ApplicationContext to be serializable).

2015-02-24 12:27:51.867  WARN 27292 --- [ost-startStop-2] o.a.c.c.C.[Catalina].[localhost].[/]     : Cannot serialize session attribute com.vaadin.server.VaadinSession.springAwareVaadinServlet for session E2EECDD1817159D3FDAE9F112969905E

java.io.NotSerializableException: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
	at org.apache.catalina.session.StandardSession.writeObject(StandardSession.java:1695)
	at org.apache.catalina.session.StandardSession.writeObjectData(StandardSession.java:1101)
	at org.apache.catalina.session.StandardManager.doUnload(StandardManager.java:430)
	at org.apache.catalina.session.StandardManager.unload(StandardManager.java:351)
	at org.apache.catalina.session.StandardManager.stopInternal(StandardManager.java:516)

**Comment by benheilers** [comment]
I just noticed https://github.com/peholmst/vaadin4spring/issues/1 and https://github.com/peholmst/vaadin4spring/issues/154, but I think specifically declaring the class I18N to implement Serializable is still a mistake and not mentioned in those issues.

**Comment by peholmst** [comment]
Yes, you are right. I'll remove the Serializable interface until I've figured out how to make the session serializable.
