### ISSUE TITLE
Vaadin UI Mixup

### ISSUE THREAD

**Issue by enyachoke** [peholmst/vaadin4spring#205]
I keep getting this error after a some time and I can navigate my application.
```
java.lang.RuntimeException: A connector with id 70 is already registered!
        at com.vaadin.ui.ConnectorTracker.registerConnector(ConnectorTracker.java:146)
        at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:585)
        at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:621)
        at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:590)
        at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:621)
        at com.coc.ui.Projects.ProjectView.attach(ProjectView.java)
        at com.vaadin.ui.AbstractComponent.setParent(AbstractComponent.java:528)
        at com.coc.ui.Projects.ProjectView.setParent(ProjectView.java)
        at com.vaadin.ui.AbstractComponentContainer.addComponent(AbstractComponentContainer.java:210)
        at com.vaadin.ui.CssLayout.addComponent(CssLayout.java:123)
        at com.vaadin.navigator.Navigator$ComponentContainerViewDisplay.showView(Navigator.java:190)
        at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:574)
        at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:526)
        at com.coc.ui.Menu$5.buttonClick(Menu.java:164)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
        at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:977)
        at com.vaadin.ui.Button.fireClick(Button.java:393)
        at com.vaadin.ui.Button$1.click(Button.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168)
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118)
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:291)
        at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:184)
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1408)
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:350)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.vaadin.spring.http.HttpResponseFilter.doFilter(HttpResponseFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

```
I also get this right before the error above
```
2015-03-09 11:33:24.006  WARN 13024 --- [nio-8080-exec-8] com.vaadin.ui.ConnectorTracker           : An already registered connector was registered again: VerticalLayout (39)
2015-03-09 11:33:24.006  WARN 13024 --- [nio-8080-exec-8] com.vaadin.ui.ConnectorTracker           : An already registered connector was registered again: HorizontalLayout (40)
2015-03-09 11:33:24.006  WARN 13024 --- [nio-8080-exec-8] com.vaadin.ui.ConnectorTracker           : An already registered connector was registered again: FormLayout (41)
2015-03-09 11:33:24.006  WARN 13024 --- [nio-8080-exec-8] com.vaadin.ui.ConnectorTracker           : An already registered connector was registered again: MTextField (42)
2015-03-09 11:33:24.006  WARN 13024 --- [nio-8080-exec-8] com.vaadin.ui.ConnectorTracker           : An already registered connector was registered again: ElementCollectionField (43)
2015-03-09 11:33:24.007  WARN 13024 --- [nio-8080-exec-8] com.vaadin.ui.ConnectorTracker           : An already registered connector was registered again: GridLayout (44)
2015-03-09 11:33:24.007  WARN 13024 --- [nio-8080-exec-8] com.vaadin.ui.ConnectorTracker           : An already registered connector was registered again: MHorizontalLayout (45)
2015-03-09 11:33:24.007  WARN 13024 --- [nio-8080-exec-8] com.vaadin.ui.ConnectorTracker           : An already registered connector was registered again: PrimaryButton (46)
2015-03-09 11:33:24.007  WARN 13024 --- [nio-8080-exec-8] com.vaadin.ui.ConnectorTracker           : An already registered connector was registered again: MButton (47)
2015-03-09 11:33:24.007  WARN 13024 --- [nio-8080-exec-8] com.vaadin.ui.ConnectorTracker           : An already registered connector was registered again: DeleteButton (48)
2015-03-09 11:33:27.637  WARN 13024 --- [nio-8080-exec-3] com.vaadin.ui.ConnectorTracker           : An already registered connector was registered again:  (52)

```
I noticed the SpringAwareUIProvider keeps scanning for uis several time note this 
```
2015-03-09 11:09:39.832  INFO 11687 --- [nio-8080-exec-1] o.v.s.servlet.SpringAwareUIProvider      : Checking the application context for Vaadin UIs
2015-03-09 11:09:39.837  INFO 11687 --- [nio-8080-exec-1] o.v.s.servlet.SpringAwareUIProvider      : Found Vaadin UI [com.coc.ui.MainUI]
2015-03-09 11:10:43.825  INFO 11687 --- [nio-8080-exec-9] o.v.s.servlet.SpringAwareUIProvider      : Checking the application context for Vaadin UIs
2015-03-09 11:10:43.829  INFO 11687 --- [nio-8080-exec-9] o.v.s.servlet.SpringAwareUIProvider      : Found Vaadin UI [com.coc.ui.MainUI]

```

My guess is am running into this [ issue](http://stackoverflow.com/questions/23881573/vaadin-a-connector-with-id-xy-is-already-registered)

**Comment by enyachoke** [comment]
I believe it is a config issue. I set the session to 60 sec which very short. Am closing this on.

**Comment by mstahv** [comment]
It is [a minor bug in Vaadin](http://dev.vaadin.com/ticket/16348).
