### ISSUE TITLE
AuthenticationCredentialsNotFoundException

### ISSUE THREAD

**Issue by siarhei-poludvaranin** [peholmst/vaadin4spring#233]
Hello,
When I mark my view class with @Secured annotation sometimes I get this exceptoion:

...
org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:339)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:198)
...

When I test the code locally - everything works fine. But on the staging server I got such exception.
Has anyone faced it? How can I solve the problem? 
My security config is the same as shown in the security-sample.

**Comment by peholmst** [comment]
I have not been able to reproduce this so I'm closing the ticket. If you're still experiencing the problem with the latest version, we can reopen the ticket.

**Comment by silentsnooc** [comment]
I have that problem for quite a while now "[Sometimes getting AuthenticationCredentialsNotFoundException between multiple requests](http://stackoverflow.com/questions/34273755/sometimes-getting-authenticationcredentialsnotfoundexception-between-multiple-re)" but on my local machine as well.

From my stackoverflow question:

"*I am having the problem of sometimes getting a AuthenticationCredentialsNotFoundException. At the moment I am absolutely not sure what's causing this.

It is "very likely" that I'm getting this exception if I login right after the server started. After logging in I am not getting this exception - for a while. Now assume there is a request loadData(). If I repeatedly send this request to the server it appears to work for a while but then, all of a sudden, I am getting this exception again. Sometimes just once, sometimes multiple times but not "forever". Just a few exceptions and then it's working again.*"

**Comment by peholmst** [comment]
Also with the latest version of Vaadin4Spring?
