### ISSUE TITLE
ApplicationContext cannot be restarted 

### ISSUE THREAD

**Issue by monp** [peholmst/vaadin4spring#265]
I'm trying to use spring-boot-devtools. I don't know if it's the only issue but VaadinApplicationContext holds a static reference on the ApplicationContext which prevents the ApplicationContext from being restarted.

```
Caused by: java.lang.IllegalStateException: The application context has already been set. Do you have multiple instances of VaadinApplicationContext in your application?
	at org.vaadin.spring.context.VaadinApplicationContext.setApplicationContext(VaadinApplicationContext.java:56) ~[vaadin-spring-ext-core-0.0.6.RELEASE.jar:na]
	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:119) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:94) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	... 20 common frames omitted
```

**Comment by peholmst** [comment]
Which version are you using? This seems to be fixed in master?

**Comment by monp** [comment]
OK. It's working with the current snapshot version.
