### ISSUE TITLE
Authentication object is unavailable for use with @Secured after a few minutes idle

### ISSUE THREAD

**Issue by code-monk** [peholmst/vaadin4spring#28]
We have a Vaadin app running on Tomcat 7 that uses Vaadin4Spring to log in and set the SecurityContextHolder's Authentication
I've found that if the user is logged in and actively doing things the Authentication object is available and methods using the @Secured annotation work correctly.
If the user is idle for minimum 30 seconds (having logged in) and then attempts to click something on the UI that calls a @Secured method (in my case, a method in a traditional service layer class) that the AOP proxy wrapper calling that method will fail with the following exception:
````
Caused by: org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
    at org.springframework.security.access.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:339)
    at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:198)
    at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:60)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
````
Note that the web.xml session timeout is configured for 60 minutes.
I believe (this is a guess at the moment) it could be that there is some memory/thread local(?) cleanup going on that I'm not aware of during the idle time.

**Comment by GJRTimmer** [comment]
The minimal SpringSecurityFilterChain requires about 8-9 filters to work correctly.

Because this is an old issue and a spring-security sample has been provided, I'm closing this until re-opening is required.
