### ISSUE TITLE
Stopped working with Spring Boot 1.1.5.RELEASE

### ISSUE THREAD

**Issue by maksimu** [peholmst/vaadin4spring#64]
After upgrading Spring Boot to version 1.1.5 Vaadin4Spring stopped working.
Here is the error I got:

```
2014-08-12 10:40:25.709  INFO 15324 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2014-08-12 10:40:25.800 DEBUG 15324 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for controller advice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@58017a75: startup date [Tue Aug 12 10:40:21 PDT 2014]; root of context hierarchy
2014-08-12 10:40:25.848 DEBUG 15324 --- [           main] .m.m.a.ExceptionHandlerExceptionResolver : Looking for exception mappings: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@58017a75: startup date [Tue Aug 12 10:40:21 PDT 2014]; root of context hierarchy
2014-08-12 10:40:26.153  INFO 15324 --- [           main] o.v.spring.navigator.SpringViewProvider  : Looking up VaadinViews
2014-08-12 10:40:26.161  INFO 15324 --- [           main] o.v.spring.navigator.SpringViewProvider  : 14 VaadinViews found
2014-08-12 10:40:26.203  WARN 15324 --- [           main] org.vaadin.spring.security.Security      : No AccessDecisionManager set! Some security methods will not be available.
2014-08-12 10:40:26.228 ERROR 15324 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.NullPointerException: null
	at org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration.onApplicationEvent(AuthenticationManagerConfiguration.java:96)
	at org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration.onApplicationEvent(AuthenticationManagerConfiguration.java:54)
	at org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration$$EnhancerBySpringCGLIB$$be0dc42c.onApplicationEvent(<generated>)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:98)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:333)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:776)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:142)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:485)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:120)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:952)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:941)
	at com.company.ase.fms.ui.UiApp.main(UiApp.java:28)

Exception in thread "main" java.lang.NullPointerException
	at org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration.onApplicationEvent(AuthenticationManagerConfiguration.java:96)
	at org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration.onApplicationEvent(AuthenticationManagerConfiguration.java:54)
	at org.springframework.boot.autoconfigure.security.AuthenticationManagerConfiguration$$EnhancerBySpringCGLIB$$be0dc42c.onApplicationEvent(<generated>)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:98)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:333)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:776)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:142)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:485)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:120)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:952)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:941)
	at com.company.ase.fms.ui.UiApp.main(UiApp.java:28)
Disconnected from the target VM, address: '127.0.0.1:33849', transport: 'socket'

Process finished with exit code 1
```

**Comment by peholmst** [comment]
Is this problem still valid?

**Comment by GJRTimmer** [comment]
This problem does not look still valid.

Reason:
The exception being thrown is due to the fact that the springSecurity initializer cannot find an ```AccessDecisionManager```. To avoid this exception I've added a default ```AccessDesicionManager``` to the ```VaadinSecurityConfiguration``` within spring-vaadin-security. see [VaadinSecurityConfiguration#GlobalMethodSecurity](https://github.com/peholmst/vaadin4spring/blob/master/spring-vaadin-security/src/main/java/org/vaadin/spring/security/config/VaadinSecurityConfiguration.java#L119-129) see highlights.

Closed
