### ISSUE TITLE
Servlet springAwareVaadinServlet is currently unavailable

### ISSUE THREAD

**Issue by sbradeen** [peholmst/vaadin4spring#94]
Hello, 
On shutdown of Tomcat, I'm getting errors such as below, with the error forwarding continuing on until the log is full. Any ideas on what may be causing this? Or how I may be able to handle it? The 'millions of instances' for deallocation is a mystery. I am happy to provide any helpful information.  
Thanks.

Application setup:
Vaadin 7.3.5
Servlet 3.0
spring-boot 1.0.2.RELEASE
spring-boot-vaadin 0.0.2-SNAPSHOT
Tomcat 7.0.50
Java 7
@Push(transport = Transport.LONG_POLLING) is enabled

Included in application.properties:
vaadin.servlet.asyncSupported=true
vaadin.servlet.params.productionMode=false
vaadin.servlet.params.heartbeatInterval=300
vaadin.servlet.params.closeIdleSessions=true
vaadin.servlet.params.legacyPropertyToString=false
server.sessionTimeout=25

Stack trace:
2014-12-09 03:21:54.568  INFO 19115 --- [ost-startStop-2] o.a.c.c.C.[Catalina].[localhost].[/SD4]  : Closing Spring root WebApplicationContext
Dec 09, 2014 3:21:54 AM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [/SD4] registered the JDBC driver [oracle.jdbc.OracleDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Dec 09, 2014 3:21:54 AM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [/SD4] registered the JDBC driver [org.netezza.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Dec 09, 2014 3:21:54 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/SD4] appears to have started a thread named [pool-10-thread-1] but has failed to stop it. This is very likely to create a memory leak.
Dec 09, 2014 3:21:54 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/SD4] created a ThreadLocal with key of type [com.google.gson.Gson$1] (value [com.google.gson.Gson$1@62dcfc44]) and a value of type [java.util.HashMap] (value [{}]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Dec 09, 2014 3:21:54 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/SD4] created a ThreadLocal with key of type [com.google.gson.Gson$1] (value [com.google.gson.Gson$1@62dcfc44]) and a value of type [java.util.HashMap] (value [{}]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Dec 09, 2014 3:21:54 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/SD4] created a ThreadLocal with key of type [com.vaadin.util.CurrentInstance$1] (value [com.vaadin.util.CurrentInstance$1@1a360711]) and a value of type [java.util.HashMap] (value [{class com.vaadin.server.VaadinService=com.vaadin.util.CurrentInstance@5109fa88, class com.vaadin.ui.UI=com.vaadin.util.CurrentInstance@661f2048, class com.vaadin.server.VaadinSession=com.vaadin.util.CurrentInstance@5808b59}]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Dec 09, 2014 3:21:54 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/SD4] created a ThreadLocal with key of type [org.springframework.core.NamedThreadLocal] (value [Request attributes]) and a value of type [org.springframework.web.context.request.ServletRequestAttributes] (value [org.apache.catalina.connector.Request@3a3c82e1]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Dec 09, 2014 3:21:54 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/SD4] created a ThreadLocal with key of type [org.springframework.core.NamedThreadLocal] (value [Locale context]) and a value of type [org.springframework.context.i18n.SimpleLocaleContext] (value [en_US]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Dec 09, 2014 3:21:54 AM org.apache.catalina.core.StandardWrapper unload
INFO: Waiting for 7189547 instance(s) to be deallocated for Servlet [springAwareVaadinServlet]
2014-12-09 03:21:54.999  WARN 19115 --- [io-8009-exec-48] a.c.c.C.[.[.[.[springAwareVaadinServlet] : Servlet springAwareVaadinServlet is currently unavailable
2014-12-09 03:21:55.008  WARN 19115 --- [bio-8009-exec-1] a.c.c.C.[.[.[.[springAwareVaadinServlet] : Servlet springAwareVaadinServlet is currently unavailable
2014-12-09 03:21:55.008  WARN 19115 --- [bio-8009-exec-4] a.c.c.C.[.[.[.[springAwareVaadinServlet] : Servlet springAwareVaadinServlet is currently unavailable
2014-12-09 03:21:55.029  WARN 19115 --- [io-8009-exec-19] a.c.c.C.[.[.[.[springAwareVaadinServlet] : Servlet springAwareVaadinServlet is currently unavailable
2014-12-09 03:21:55.033 ERROR 19115 --- [io-8009-exec-48] a.c.c.C.[.[.[.[springAwareVaadinServlet] : Servlet.service() for servlet springAwareVaadinServlet threw exception

java.lang.IllegalStateException: Cannot forward after response has been committed
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:349)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:339)
	at org.springframework.boot.context.web.ErrorPageFilter.handleException(ErrorPageFilter.java:135)
	at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:104)
	at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:85)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:749)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:487)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:412)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:339)
	at org.springframework.boot.context.web.ErrorPageFilter.handleException(ErrorPageFilter.java:135)
	at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:104)
	at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:85)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:749)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:487)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:412)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:339)
	at org.springframework.boot.context.web.ErrorPageFilter.handleErrorStatus(ErrorPageFilter.java:119)
	at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:100)
	at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:85)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:749)

**Comment by LukaszByczynski** [comment]
This bug is related to issues with Vaadin push implementation and Tomcat. With Jetty I hadn't any issues. Check this topic at official Vaadin forum about Tomcat issues: https://vaadin.com/forum#!/thread/8232643

**Comment by sbradeen** [comment]
Thanks for the response. I am upgrading our Vaadin version, to see if it helps with the intermittent push "hang" issue. Tomcat 7 appears to be is causing some pains with the latest spring boot jpa as well.

**Comment by peholmst** [comment]
Closing since this no longer applies to Vaadin4Spring.
